CREATE TABLE IF NOT EXISTS todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO todos (title, completed)
SELECT seed.title, seed.completed
FROM (
    VALUES
        ('Wire Vue to the Spring API', true),
        ('Add your first domain feature', false)
) AS seed(title, completed)
WHERE NOT EXISTS (
    SELECT 1
    FROM todos
);
