CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    category VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_image_urls (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    PRIMARY KEY (product_id, sort_order)
);

INSERT INTO products (name, description, price, stock_quantity, category, active)
SELECT seed.name, seed.description, seed.price, seed.stock_quantity, seed.category, seed.active
FROM (
    VALUES
        ('Everyday Backpack', 'Durable backpack with room for a laptop and daily carry.', 89.00, 24, 'Bags', true),
        ('Ceramic Mug', 'Minimal 12 oz mug for coffee or tea.', 18.50, 60, 'Home', true)
) AS seed(name, description, price, stock_quantity, category, active)
WHERE NOT EXISTS (
    SELECT 1
    FROM products
);
